name: Publish

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - 1.67.0
          - 1.82.0
          - 2.48.0
          - 2.63.0
          - 2.68.0
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u irrelevant-user --password-stdin
          docker build --build-arg SERVERLESS_VERSION=${{ matrix.version }} -t ghcr.io/mybuilder/serverless:${{ matrix.version }} .
          docker push ghcr.io/mybuilder/serverless:${{ matrix.version }}
