name: Publish

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - 1.67.0
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login -u mybuilderautomation --password-stdin
          docker build --build-arg SERVERLESS_VERSION=${{ matrix.version }} -t mybuilder/serverless:${{ matrix.version }} .
          docker push mybuilder/serverless:${{ matrix.version }}
